// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Las migraciones (DDL) usan la conexión DIRECTA. En prod (Vercel + Neon),
    // DATABASE_URL apunta al endpoint POOLED (PgBouncer) para el runtime serverless,
    // que no soporta bien el DDL; por eso migramos contra DIRECT_URL. En dev no existe
    // ese split, así que cae a DATABASE_URL y nada cambia localmente.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
